service: serverless-email-inbox

provider:
  name: aws
  runtime: nodejs12.x
  stage: prod
  region: eu-west-1
  stackName: serverless-email-inbox-stack
  apiName: serverless-email-inbox-api
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 's3:*'
      Resource: 'arn:aws:s3:::email.nicholasgriffin.dev/*'

package:
  patterns:
    - '!config/**'
    - '!.eslintrc.js'
    - '!package-lock.json'
    - '!package.json'
    - '!yarn.lock'
    - 'config.js'

functions:
  inbox:
    handler: handler.inbox
    description: Parse email from SES
    timeout: 15
